---
name: Mark the commit deployable
on:
  push:
    branches:
      - main

jobs:
  report-status:
    runs-on: ubuntu-latest
    steps:
    - name: Create GitHub deployment (pending)
      uses: sergioramos/yet-another-deployment-action/create@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: production
        production_environment: true
        ref: ${{ github.head_ref || github.ref }}
        state: 'pending'

    - run: echo "yayyy"
      name: actual deploy steps


    - name: Create GitHub deployment (success)
      uses: sergioramos/yet-another-deployment-action/create@v1
      if: success()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        environment: production
        production_environment: true
        environment_url: 'https://env.url'
        ref: ${{ github.head_ref || github.ref }}
        state: 'success'
    - name: Create GitHub deployment (failure)
      uses: sergioramos/yet-another-deployment-action/create@v1
      if: failure()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        production_environment: true
        environment: production
        ref: ${{ github.head_ref || github.ref }}
        state: 'failure'
